#bhai log kya hal hai
#print("please subscribe to my channal")
"""multiline 
comment 
yehi 
hota hai """
"""
print("bhai log please subscribe karoo",end="" )
print("tashanditya ko subscribe karoo dostoo") """ #ye do line me print kar raha hai but ek line me print karwaane ke liye """"""
"""
print("My name is Aditya kashyap", end=" ")
print("Currently I am in 5th sem")
print("ankit is my name", end=" but some people know me as ")
print("Aditya")"""
"""
print("c:\harry")
print("c:\narry")
print("c:\\narry")
"""
"""
li = [1,2,3,'a','b','c']
'a' in li
#=> True
"""
"""
print("c:\Aditya")
print("c:\\Aditya")
print("c:\"aditya") 
"""
# dekhoo aasise print karwana hoo gaa

#print("Aditya is a \n good boy \t 1")
#
# for i in range(6):
#     print((" @ "*i).center(15))
#
# for i in range(6):
#     for x in range(6-i):
#         print(" ",end=" ")
#     for y in range(6-x):
#         print(" * ",end=" ")
#
#     print()
# #
# #
# for i in range(4):
#     for x in range(i+1):
#         print(" * ", end=" ")
#     print()
# opens test.text file of the current directory
# opens test.text file of the current directory
# f = open("test.txt")
#
# # specifying the full path
# f = open("C:/Python33/README.txt")
# file = open('C:\Users\kashy\PycharmProjects\firstprog\code_wid_harry.py','r')
# for i in file
#     print(i)
    #
    # Write
    # a
    # python
    # Program
    # to
    # construct
    # the
    # following
    # pattern
    # using
    # a
    # nested
    # for loop.
    #
    # *
    # * *
    # * * *
    # * * * *
    # * * *
    # * *
    # *

n = 4;
for i in range(n):
    for j in range(i):
        print(' <> ', end="")
    print('')

for i in range(n, 0, -1):
    for j in range(i):
        print(' <> ', end="")
    print('')

# n = 6;
# for i in range(n):
#     for j in range(i):
#         print(' $ ', end="")
#         print('')
#
# for i in range(n, 0, -1):
#     for j in range(1):
#         print(' @ ', eng="")
#         print('')


print("enter the marks")
marks=int(input())
if marks<25:
    print("f")
elif marks <25 and marks >45:
    print("e")
elif marks <45 and marks >50:
    print("d")
elif marks <50 and marks >60:
    print("c")
elif marks <60 and marks >80:
    print("b")
else:
    print("a")

    # n = 4;
    # for i in range(n):
    #     for j in range(i):
    #         print(' <> ', end="")
    #     print('')
    #
    # for i in range(n, 0, -1):
    #     for j in range(i):
    #         print(' <> ', end="")
    #     print('')
